export let testinomial_data = [
  {
    name: "MOHIT",
    desc: "mohit desc",
    linkedIn_url: "",
    image_url: "https://avatars.githubusercontent.com/u/1?v=4",
  },
  {
    name: "NAG",
    desc: "nag desc",
    linkedIn_url: "",
    image_url: "https://avatars.githubusercontent.com/u/2?v=4",
  },

  {
    name: "MOHIT",
    desc: "mohit desc",
    linkedIn_url: "",
    image_url: "https://avatars.githubusercontent.com/u/1?v=4",
  },
  {
    name: "NAG",
    desc: "nag desc",
    linkedIn_url: "",
    image_url: "https://avatars.githubusercontent.com/u/2?v=4",
  },
  {
    name: "MOHIT",
    desc: "mohit desc",
    linkedIn_url: "",
    image_url: "https://avatars.githubusercontent.com/u/1?v=4",
  },
  {
    name: "NAG",
    desc: "nag desc",
    linkedIn_url: "",
    image_url: "https://avatars.githubusercontent.com/u/2?v=4",
  },
  {
    name: "RAHUL",
    desc: "rahul desc",
    linkedIn_url: "",
    image_url: "",
  },
  {
    name: "TEST1",
    desc: "test desc",
    linkedIn_url: "",
    image_url: "",
  },
  {
    name: "TEST2",
    desc: "test desc",
    linkedIn_url: "",
    image_url: "",
  },
  {
    name: "",
    desc: "",
    linkedIn_url: "",
    image_url: "",
  },
  {
    name: "",
    desc: "",
    linkedIn_url: "",
    image_url: "",
  },
  {
    name: "MOHIT",
    desc: "mohit desc",
    linkedIn_url: "",
    image_url: "https://avatars.githubusercontent.com/u/1?v=4",
  },
  {
    name: "NAG",
    desc: "nag desc",
    linkedIn_url: "",
    image_url: "https://avatars.githubusercontent.com/u/2?v=4",
  },
  {
    name: "",
    desc: "",
    linkedIn_url: "",
    image_url: "",
  },
  {
    name: "",
    desc: "",
    linkedIn_url: "",
    image_url: "",
  },
  {
    name: "MOHIT",
    desc: "mohit desc",
    linkedIn_url: "",
    image_url: "https://avatars.githubusercontent.com/u/1?v=4",
  },
  {
    name: "NAG",
    desc: "nag desc",
    linkedIn_url: "",
    image_url: "https://avatars.githubusercontent.com/u/2?v=4",
  },
  {
    name: "",
    desc: "",
    linkedIn_url: "",
    image_url: "",
  },
  {
    name: "",
    desc: "",
    linkedIn_url: "",
    image_url: "",
  },
  {
    name: "",
    desc: "",
    linkedIn_url: "",
    image_url: "",
  },
  {
    name: "",
    desc: "",
    linkedIn_url: "",
    image_url: "",
  },
];
